

services:
  redis:
    image: redis:alpine
    container_name: communitygo-redis-1
    ports:
      - "6379:6379"
    restart: always

  db:
    image:  postgis/postgis:15-3.4
    container_name: communitygo-postgres-1
    # env_file:
    #   - ./backend/.env
    environment:
      POSTGRES_USER: don
      POSTGRES_PASSWORD: don@mydb   # Set a password here
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U don -d mydb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app  
      - /app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    restart: always

  # frontend:
  #   image: communitygo-frontend
  #   ports:
  #     - "3000:80"
  #   volumes:
  #     - ./frontend:/app  
  #     - /app/node_modules
  #   env_file:
  #     - ./frontend/.env
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
      - "8001:8001"  # Added port for Daphne

    volumes:
      - ./backend:/app  
      - /tmp/daphne.sock:/tmp/daphne.sock
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://don:don@mydb@db:5432/mydb

    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

    restart: always

  # backend:
  #   image: sarath583364/teamlink-backend:latest
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"  
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DJANGO_SETTINGS_MODULE=backend.settings
  #   depends_on:
  #     - redis
  #     - db
  #   restart: always

  # daphne:
  #   image: sarath583364/teamlink-backend
  #   command: daphne -u /tmp/daphne.sock backend.asgi:application
  #   volumes:
  #     - /tmp/daphne.sock:/tmp/daphne.sock
  #   env_file:
  #     - ./backend/.env
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #   depends_on:
  #     - redis
  #     - db
  #   restart: always


  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - GDAL_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/libgdal.so
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://don:don@mydb@db:5432/mydb
    depends_on:
      - redis
      - backend
    restart: always

  # postgres:
  #   image: postgres:15
  #   container_name: communitygo-postgres-1
  #   environment:
  #     - POSTGRES_USER=don
  #     - POSTGRES_PASSWORD=don@mydb
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data



  # nginx:
  #   image: teamlink-nginx
  #   ports:
  #     - "80:80"  
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - static_volume:/app/static  
  #     - media_volume:/app/media    
  #   depends_on:
  #     - frontend
  #     - backend
  #   restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: