# Dockerfile.backend

# Stage 1: Build stage
FROM python:3.12-slim as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    python3-gdal \
    gcc \
    gdal-bin \
    libgdal-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=backend.settings
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_LIBRARY=/usr/lib/x86_64-linux-gnu/libgdal.so

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir setuptools wheel \
    && pip install --no-cache-dir GDAL==`gdal-config --version` \
    && pip install --no-cache-dir -r requirements.txt

# Stage 2: Production stage
FROM python:3.12-slim

# Install system GDAL dependencies
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_LIBRARY=/usr/lib/x86_64-linux-gnu/libgdal.so 
ENV LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH


WORKDIR /app

# Copy Python packages from builder
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy project files
COPY . /app/

# Ensure Gunicorn and Daphne are available
RUN pip install gunicorn daphne channels-redis

# Command to run both Gunicorn and Daphne
# CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --workers 3 & daphne -u /tmp/daphne.sock backend.asgi:application"]
# CMD ["sh", "-c", "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --workers 3 & daphne -b 0.0.0.0 -p 8001 backend.asgi:application"]
# In Dockerfile.backend, update the CMD line to:
CMD ["sh", "-c", "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --workers 3 & daphne -b 0.0.0.0 -p 8001 backend.asgi:application"]