# Dockerfile.backend

# Stage 1: Build stage
FROM python:3.12-slim as builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    gcc \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=backend.settings
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal
ENV GDAL_LIBRARY=/usr/lib/x86_64-linux-gnu/libgdal.so

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip \
    && pip install --no-cache-dir \
        setuptools \
        wheel \
        numpy \
        GDAL==3.6.2 \
    && pip install --no-cache-dir -r requirements.txt

# Stage 2: Production stage
FROM python:3.12-slim

# Install system GDAL dependencies
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copy Python packages from builder
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Copy project files
COPY . /app/

# Ensure Gunicorn and Daphne are available
RUN pip install gunicorn daphne channels-redis

# Command to run both Gunicorn and Daphne
CMD ["sh", "-c", "gunicorn --bind 0.0.0.0:8000 backend.wsgi:application --workers 3 & daphne -u /tmp/daphne.sock backend.asgi:application"]