# Generated by Django 5.1.4 on 2024-12-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
