# Generated by Django 5.1.4 on 2024-12-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0002_delivery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
