# Generated by Django 5.1.4 on 2024-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0003_delivery_height_delivery_length_delivery_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='est_dropoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='est_pickup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
