# Generated by Django 5.1.4 on 2025-01-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0004_delivery_est_dropoff_delivery_est_pickup'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.transaction'),
        ),
    ]
