# Generated by Django 5.1.4 on 2025-01-09 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_delivery_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
