# Generated by Django 5.1.3 on 2024-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0005_rename_deliver_otp_delivery_dropoff_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PENDING', max_length=12),
        ),
    ]
