# Generated by Django 5.1.4 on 2025-01-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0006_delivery_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=110, max_digits=10),
            preserve_default=False,
        ),
    ]
