# Generated by Django 5.1.4 on 2025-01-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0007_delivery_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
