# Generated by Django 5.1.4 on 2025-01-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0008_alter_delivery_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
