# Generated by Django 5.1.4 on 2025-01-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0009_delivery_payment_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='PAYMENT', max_length=12),
        ),
    ]
