# Generated by Django 5.1.3 on 2024-12-01 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0010_alter_delivery_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='Delivery.delivery'),
        ),
    ]
