# Generated by Django 5.1.3 on 2024-12-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0011_alter_courier_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addresses',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
