# Generated by Django 5.1.4 on 2024-12-05 12:17

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0012_addresses_latitude_addresses_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
