# Generated by Django 5.1.4 on 2024-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0013_addresses_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courier',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
