# Generated by Django 5.1.4 on 2024-12-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0015_delivery_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_pickedup',
            field=models.BooleanField(default=False),
        ),
    ]
