# Generated by Django 5.1.4 on 2024-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery', '0016_delivery_is_pickedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='feedback',
            field=models.CharField(blank=True, null=True),
        ),
    ]
