# Generated by Django 5.1.4 on 2024-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rideroute',
            old_name='latitude',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='rideroute',
            old_name='longitude',
            new_name='end_longitude',
        ),
        migrations.AddField(
            model_name='rideroute',
            name='start_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rideroute',
            name='start_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
