# Generated by Django 5.1.4 on 2024-12-31 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0002_rename_latitude_rideroute_end_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
