# Generated by Django 5.1.4 on 2025-01-01 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0003_alter_ride_starting_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ridepartner',
            old_name='latitude',
            new_name='pickup_latitude',
        ),
        migrations.RenameField(
            model_name='ridepartner',
            old_name='longitude',
            new_name='pickup_longitude',
        ),
    ]
