# Generated by Django 5.1.4 on 2025-01-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0004_rename_latitude_ridepartner_pickup_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepartner',
            name='dropoff_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridepartner',
            name='dropoff_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
