# Generated by Django 5.1.4 on 2025-01-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0005_ridepartner_dropoff_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='booked_seats',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ridepartner',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
