# Generated by Django 5.1.4 on 2025-01-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0006_ride_booked_seats_ridepartner_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='booked_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ridepartner',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
