# Generated by Django 5.1.4 on 2025-01-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0007_alter_ride_booked_seats_alter_ridepartner_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='booked_seats',
            new_name='total_seats',
        ),
        migrations.AlterField(
            model_name='ride',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
