# Generated by Django 5.1.4 on 2025-01-01 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0008_rename_booked_seats_ride_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pickedup', 'Pickedup'), ('dropedoff', 'Dropedoff')], default='pending', max_length=25),
        ),
    ]
