# Generated by Django 5.1.4 on 2025-01-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0009_ridepartner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridepartner',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pickedup', 'Pickedup'), ('dropedoff', 'Dropedoff'), ('cancled', 'Cancled')], default='pending', max_length=25),
        ),
    ]
