# Generated by Django 5.1.4 on 2025-01-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('RideShare', '0010_alter_ridepartner_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.transaction'),
        ),
    ]
