# Generated by Django 5.1.4 on 2025-01-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0012_remove_ride_transaction_ridepartner_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ridepartner',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
