# Generated by Django 5.1.4 on 2025-01-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0013_ride_amount_ridepartner_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepartner',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
