# Generated by Django 5.1.4 on 2025-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0014_ridepartner_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepartner',
            name='feedback',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridepartner',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
