# Generated by Django 5.1.4 on 2025-01-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideShare', '0015_ridepartner_feedback_ridepartner_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ridepartner',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ridepartner',
            name='status',
            field=models.CharField(choices=[('payment', 'Payment'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pickedup', 'Pickedup'), ('dropedoff', 'Dropedoff'), ('cancled', 'Cancled')], default='payment', max_length=25),
        ),
    ]
