# Generated by Django 5.1.4 on 2025-01-10 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_rename_wallet_myearnings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myearnings',
            old_name='balance',
            new_name='earnings',
        ),
        migrations.AddField(
            model_name='myearnings',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='EarningsTransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('earnings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.myearnings')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.transaction')),
            ],
        ),
    ]
