# Generated by Django 5.1.4 on 2025-01-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_rename_balance_myearnings_earnings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earningstransactionlog',
            name='earnings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.myearnings'),
        ),
    ]
