# Generated by Django 5.1.4 on 2025-01-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_email_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
