# Generated by Django 5.1.4 on 2025-01-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_otprecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
