# Generated by Django 5.1.4 on 2025-01-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_otprecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='admin_verified',
            field=models.BooleanField(default=False),
        ),
    ]
